# Reference: 
# https://dev.to/pacheco/how-to-dockerize-a-node-app-and-deploy-to-heroku-3cch#prod-env-dockerfile
# https://blog.mikesir87.io/2018/07/leveraging-multi-stage-builds-single-dockerfile-dev-prod/

version: "3.7"
services:
    api:
        image: book-hunt-api:prod
        container_name: book-hunt-api
        env_file: .env
        build:
            context: .
            dockerfile: ./Dockerfile
            target: prod
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 80:3000
        restart: always
        # depends_on:
        #     - db
        networks: 
            - book-hunt-api-network

    # db:
    #     image: mongo
    #     restart: always
    #     container_name: book-hunt-api-mongo
    #     ports:
    #         - 27017:27017 
    #     volumes:
    #         - book-hunt-api-mongo:/data/db
    #     networks: 
    #         - book-hunt-api-network

# volumes: 
#     book-hunt-api-mongo:
#         name: book-hunt-api-mongo
    
networks: 
    book-hunt-api-network:
        name: book-hunt-api-network